name: nefer_functions
description: Firebase Cloud Functions for Nefer E-commerce App written in Dart
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  functions_framework: ^0.4.0
  firebase_admin: ^0.3.0
  shelf: ^1.4.1
  shelf_cors: ^1.0.2
  shelf_router: ^1.1.4
  http: ^1.1.2
  crypto: ^3.0.3
  uuid: ^4.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  collection: ^1.18.0
  meta: ^1.11.0
  logging: ^1.2.0
  dotenv: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.9
  lints: ^3.0.0

executables:
  server: main
