arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: l10n.dart
output-class: AppLocalizations
output-dir: lib/generated
nullable-getter: false
synthetic-package: false
header-file: lib/l10n/header.txt
header: |
  /// Nefer E-commerce App Localizations
  /// Generated on: {date}
  /// 
  /// This file contains all the localized strings for the Nefer application.
  /// 
  /// Supported languages:
  /// - English (en)
  /// - Arabic (ar)
use-deferred-loading: false
gen-inputs-and-outputs-list: lib/l10n/l10n_inputs_and_outputs.json
