name: nefer
description: "Nefer (نفِر) - Pharaonic E-commerce App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2
  cloud_functions: ^6.0.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0+8
  firebase_messaging: ^15.1.3

  # UI & Animations
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  image: ^4.1.3

  # Navigation & Routing
  go_router: ^12.1.3
  auto_route: ^7.8.4

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Network & HTTP
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  # Utilities
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1

  # Image Processing
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0

  # Payment
  flutter_stripe: ^11.5.0
  # paypal_flutter: ^1.0.0  # Add if using PayPal

  # Forms & Validation
  reactive_forms: ^16.1.1
  email_validator: ^2.1.17

  # Date & Time
  timeago: ^3.6.0

  # Logging
  logger: ^2.0.2+1

  # Additional UI Components
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  data_table_2: ^2.5.15
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  photo_view: ^0.15.0

  # Maps & Location
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.0

  # Notifications
  flutter_local_notifications: ^17.2.3
  awesome_notifications: ^0.9.3+1

  # Audio & Video
  just_audio: ^0.9.40
  video_player: ^2.9.1
  camera: ^0.11.0+2

  # PDF & Documents
  pdf: ^3.11.1
  printing: ^5.13.2
  open_file: ^3.5.7

  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  # Charts & Analytics
  fl_chart: ^0.69.0

  # Additional Animations
  rive: ^0.13.13
  flutter_animate: ^4.5.0
  confetti: ^0.7.0

  # Utils
  uuid: ^4.5.1
  crypto: ^3.0.3
  path_provider: ^2.1.4

  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  fake_cloud_firestore: ^2.4.1+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - .env.dev
    - .env.staging
    - .env.prod

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cinzel-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cinzel-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
