// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7wWai6Te6KFhjlm_2-fxfT6bnVXgDuGU',
    appId: '1:448618578101:web:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'nefer-ecommerce',
    authDomain: 'nefer-ecommerce.firebaseapp.com',
    databaseURL: 'https://nefer-ecommerce-default-rtdb.firebaseio.com',
    storageBucket: 'nefer-ecommerce.appspot.com',
    measurementId: 'G-9JSH4MXFMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrZ96oOfz2oHDOWQESCqc',
    appId: '1:448618578101:android:aa79a439fcb8580fac3efc',
    messagingSenderId: '448618578101',
    projectId: 'nefer-ecommerce',
    databaseURL: 'https://nefer-ecommerce-default-rtdb.firebaseio.com',
    storageBucket: 'nefer-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHAsf51D3A407EhC64b0H8t-0a58as1Ro',
    appId: '1:448618578101:ios:2bd1406f50cdd52fac3efc',
    messagingSenderId: '448618578101',
    projectId: 'nefer-ecommerce',
    databaseURL: 'https://nefer-ecommerce-default-rtdb.firebaseio.com',
    storageBucket: 'nefer-ecommerce.appspot.com',
    iosBundleId: 'com.nefer.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHAsf51D3A407EhC64b0H8t-0a58as1Ro',
    appId: '1:448618578101:ios:2bd1406f50cdd52fac3efc',
    messagingSenderId: '448618578101',
    projectId: 'nefer-ecommerce',
    databaseURL: 'https://nefer-ecommerce-default-rtdb.firebaseio.com',
    storageBucket: 'nefer-ecommerce.appspot.com',
    iosBundleId: 'com.nefer.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7wWai6Te6KFhjlm_2-fxfT6bnVXgDuGU',
    appId: '1:448618578101:web:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'nefer-ecommerce',
    authDomain: 'nefer-ecommerce.firebaseapp.com',
    databaseURL: 'https://nefer-ecommerce-default-rtdb.firebaseio.com',
    storageBucket: 'nefer-ecommerce.appspot.com',
    measurementId: 'G-9JSH4MXFMV',
  );
}
